name: Unit test

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            
            - name: Install Package Manager (pnpm)
              run: npm i -g pnpm
            
            - name: Install Dependencies for Parcol
              run: pnpm i
            
            - name: Start Tests with Jest
              run: pnpm test